# -*- coding: utf-8 -*-
"""
Created on Fri Aug 29 19:26:03 2025

@author: akos
"""

import sys
import os
sys.path.append(os.path.dirname(__file__))
import functions as func


import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib import gridspec



def ref_data(reflectometer):
    """
    Generate a summary string with key properties of a reflectometer.

    Parameters
    ----------
    reflectometer : An object representing a reflectometer. 

    Returns
    -------
    str
        A formatted string summarizing the reflectometer properties, e.g.:
        Solver, Wavemode, Beam waist in mm, and Angle with sign.
    """
    ref = reflectometer
    text = '\n'.join((f"Solver: {ref.solver}",
                      f"Wavemode: {ref.wavemode}",
                      f"Beam w.: {ref.beam_waist_si*1e3} mm",
                      f"Angle: {ref.angle:+}°"))
    return text

def cwt_data(data, frequency_index):
    f = frequency_index
    text = '\n'.join(("Event estimation",
        "Time: {:.2f} [\u00B5s]".format(data['x0'][f]*1e6),
        "Start/end: {:.1f}/".format(data['FWHM_lims'][f, 0]*1e6) +
        "{:.1f} [\u00B5s]".format(data['FWHM_lims'][f, 1]*1e6) ),
        "CWT coeff.: {:.2f} [1e-3]".format(data['A'][f]*1e3),
        "Wave freq.: {:.3f} [MHz]".format(1/data['y0'][f]*1e-6))
    
    return text

def plot_EZ_field(data, filename = False, show = False, 
                  reflectometer = None, text = None, figsize=(5, 5*1.5)):
    
    # setting the axis and field data
    ref = reflectometer
    # if(ref != None):
    #     if(hasattr(ref, "setup_map")):
    #             X, Y = ref.setup_map["X_abs"]*1e3, ref.setup_map["Y_abs"]*1e3
    #     else:   X, Y = ref.x*1e3, ref.y*1e3
    # else:       
    Y, X = np.arange(data.shape[0]), np.arange(data.shape[1])
    Z = data
    maximum = max(abs(np.max(Z)), abs(np.min(Z)))
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10, 0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z, levels=200, cmap="RdBu_r",
                          vmin=-maximum, vmax=maximum)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
        ax.plot(xs, ys, c = "black", linestyle= "--")
    
    # Create the appropriate annotations
    ax.set_title("Electromagnetic field", loc = "center")
    ax.set_xlabel("Radial position x [mm]")
    ax.set_ylabel("Poloidal position y [mm]")
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax
    
    return fig, ax
    
def plot_amplitude_field(data, filename = False, show = False, text = None,
                         figsize=(8, 5)):
    """
    Plot the amplitude response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "amplitude_field": 2D array of amplitude values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    ampl = ax.contourf(data["time"] *1e6, data["frequencies"], 
                       data["amplitude_field"].T, levels=200, cmap='jet')
    ax.set_title("Amplitude response field")
    ax.set_ylabel("Frequency f [GHz]")
    ax.set_xlabel("Time t [\u00B5s]")
    fig.colorbar(ampl, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_phase_field(data, filename = False, show = False, text = None,
                     figsize=(8, 5)):
    """
    Plot the phase response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "phase_field": 2D array of phase values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """
    max_val = max(abs(np.max(data["phase_field"])),
                  abs(np.min(data["phase_field"])))
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    phas = ax.contourf(data["time"] *1e6, data["frequencies"], 
                       data["phase_field"].T, levels=200, cmap='coolwarm',
                       vmin=-max_val, vmax=max_val)
    ax.set_title("Phase response field")
    ax.set_ylabel("Frequency f [GHz]")
    ax.set_xlabel("Time t [\u00B5s]")
    fig.colorbar(phas, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_phase_grad_field(data, filename = False, show = False, text = None,
                          figsize=(8, 5)):
    """
    Plot the phase response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "phase_field": 2D array of phase values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """

    max_val = 2 #max(abs(np.max(data["phase_grad_field"])),


                  #abs(np.min(data["phase_grad_field"])))
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    phas = ax.contourf(data["time"] *1e6, data["frequencies"], 
                       data["phase_grad_field"].T, levels=200, cmap='coolwarm',
                       vmin=-max_val, vmax=max_val)
    ax.set_title("Phase gradient response field")
    ax.set_ylabel("Frequency f [GHz]")
    ax.set_xlabel("Time t [\u00B5s]")
    fig.colorbar(phas, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_cwt(data, filename = False, show = False, text = None, 
             frequency_index = 0, figsize=None,
             event = None, signal = None, gauss_fit = False):
    """
    Plot the Continuous Wavelet Transform as an image plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "phase_field": 2D array of phase values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """
    f = frequency_index
    freq = data["frequencies"][data["frequency_indices"][f]]
    tu = 1e-6 # unit of time (microseconds)
    cwt = data["cwt_matrix"][f, :, :]
    gauss = data["gauss_fit"][f, :, :]
    t = data["time"]/tu
    T = data["period"]/tu
    
    
    if(signal is not None):
        # --- Define figure ---
        if figsize is None: figsize = (9,6)
        fig = plt.figure(figsize=figsize, dpi=100)
        
        # --- Define the grid for the subplots --- 
        gs = gridspec.GridSpec( 2, 2, width_ratios=[20, 0.5], 
                height_ratios=[0.8, 3], hspace=0.1, wspace=0.3)

        # --- Subplots ---
        axs = [fig.add_subplot(gs[0, 0])]
        axs.append(fig.add_subplot(gs[1, 0], sharex=axs[0]))
        cax = fig.add_subplot(gs[1, 1])  # colorbar axis
        
        # --- Complex signal - time series ---
        axs[0].plot(t, signal[:, f].imag, color='tab:orange')
        axs[0].plot(t, signal[:, f].real, color='tab:blue')
        
        # --- Time-frequency field | cwt transform ---
        im = axs[1].imshow(np.abs(cwt), extent = [t[0], t[-1], T[-1], T[0]], 
                            aspect='auto', cmap='jet')
        # t - time series, T - wavelet waveperiod (freq on twin axis)
        
        # --- Set the ax parameters ---
        title = (f"Complex signal and its Continuous Wavelet Transform" +
                 f" | {freq:.1f} GHz")
        axs[0].set_title(title, fontweight='bold')
        axs[0].set_ylabel("Signal")
        axs[0].grid(True, alpha=0.3)
        axs[0].tick_params(axis='x', which='both', bottom=0, labelbottom=0)
        axs[0].legend([r"$\Re$", r"$\Im$"], loc = 'lower left')
        axs[1].set_ylabel("Wave period Ts [\u00B5s]")
        axs[1].set_xlabel("Time t [\u00B5s]")
        axs[1].grid(True, alpha=0.3)
        
        # --- Twin axis for frequency of the sampling wavelet ---
        axs_twin = axs[1].twinx()
        axs_twin.set_ylim(axs[1].get_ylim())  # align scales
        yticks = axs[1].get_yticks()[1:-1]
        axs_twin.set_yticks(yticks)
        axs_twin.set_yticklabels([f"{1/f:.3f}" for f in yticks])
        axs_twin.set_ylabel("Frequency fs [MHz]")
        
        # --- Colorbar ---
        cb = plt.colorbar(im, cax=cax)
        cb.ax.ticklabel_format(style='sci', scilimits=(0, 0))
        cb.set_label("CWT Coefficient")
        
        # --- Event localisation ---
        if (event is not None):
            # scatter: maximum of wavelet transform (gauss fit)
            # event start/end: FWHM along the x axis (gauss fit)
            (i1,i2) = event["FWHM_inds"][f, :]
            
            axs[1].scatter(event["x0"][f]/tu, event["y0"][f]/tu,
                           color = "black")
            axs[1].plot([t[i1], t[i1]], [T[0], T[-1]])
            axs[1].plot([t[i2], t[i2]], [T[0], T[-1]])
        
        # Extra infromation in textbox
        if (text is not None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.7)
            axs[1].text(0.05, 0.95, text, transform=axs[1].transAxes,
                        fontsize=10, verticalalignment='top', bbox=props)
            
    
    elif (gauss_fit):
        vmin = min(np.abs(cwt).min(), np.abs(gauss).min())
        vmax = max(np.abs(cwt).max(), np.abs(gauss).max())
        
        # --- Define figure ---
        if figsize is None: figsize = (8,7)
        fig = plt.figure(figsize=figsize, dpi=100)
        
        # --- Define the grid for the subplots --- 
        gs = gridspec.GridSpec(2, 2, width_ratios=[20, 0.8],
            height_ratios=[1, 1], hspace=0.2, wspace=0.3)
        
        # --- Subplots ---
        axs = [fig.add_subplot(gs[0, 0])]
        axs.append(fig.add_subplot(gs[1, 0], sharex=axs[0], sharey=axs[0]))
        cax = fig.add_subplot(gs[:, 1])  # colorbar spans both rows
        
        # --- Continuous Wavelet Transform ---
        im = axs[0].imshow(np.abs(cwt), extent = [t[0], t[-1], T[-1], T[0]], 
                           aspect='auto', cmap='jet', vmin=vmin, vmax=vmax)
        # t - time series, T - wavelet waveperiod (freq on twin axis)
        
        # --- Fitted asymmetric Gauss ---
        im = axs[1].imshow(np.abs(gauss), extent = [t[0], t[-1], T[-1], T[0]], 
                           aspect='auto', cmap='jet', vmin=vmin, vmax=vmax)
        # t - time series, T - wavelet waveperiod (freq on twin axis)
        
        # --- Set the ax parameters ---
        axs[0].grid(True, alpha=0.3)
        title = f"Continuous Wavelet Transform | {freq:.1f} GHz"
        axs[0].set_title(title, fontweight = 'bold')
        axs[0].set_ylabel("Wave period Ts [\u00B5s]")
        axs[0].tick_params(axis='x', which='both', bottom=0, labelbottom=0)
        axs[1].grid(True, alpha=0.3)
        axs[1].set_title("Fitted asymmetric Gauss", fontweight='bold')
        axs[1].set_ylabel("Wave period Ts [\u00B5s]")
        axs[1].set_xlabel("Time t [\u00B5s]")
        
        # --- Twin axis for frequency of event ---
        axs_twin = axs[0].twinx()
        axs_twin.set_ylim(axs[0].get_ylim())  # align scales
        yticks = axs[0].get_yticks()[1:-1]    # extract ticks
        axs_twin.set_yticks(yticks)
        axs_twin.set_yticklabels([f"{1/f:.3f}" for f in yticks])
        axs_twin.set_ylabel("Frequency fs [MHz]")
        axs_twin = axs[1].twinx()
        axs_twin.set_ylim(axs[1].get_ylim())  # align scales
        yticks = axs[1].get_yticks()[1:-1]    # extract ticks
        axs_twin.set_yticks(yticks)
        axs_twin.set_yticklabels([f"{1/f:.3f}" for f in yticks])
        axs_twin.set_ylabel("Frequency fs [MHz]")
        
        # --- Colorbar ---
        cb = plt.colorbar(im, cax=cax)
        cb.ax.ticklabel_format(style='sci', scilimits=(0, 0))
        cb.set_label("CWT Coefficient")
        
        # --- Event localisation ---
        if (event is not None):
            # scatter: maximum of wavelet transform (gauss fit)
            # event start/end: FWHM along the x axis (gauss fit)
            (i1,i2) = event["FWHM_inds"][f, :]
            
            axs[0].scatter(event["x0"][f]/tu, event["y0"][f]/tu,
                       color = "black")
            axs[0].plot([t[i1], t[i1]], [T[0], T[-1]])
            axs[0].plot([t[i2], t[i2]], [T[0], T[-1]])
            
            axs[1].scatter(event["x0"][f]/tu, event["y0"][f]/tu,
                       color = "black")
            axs[1].plot([t[i1], t[i1]], [T[0], T[-1]])
            axs[1].plot([t[i2], t[i2]], [T[0], T[-1]])
        
        # --- Extra information in textbox ---
        if (text is not None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.7)
            axs[0].text(0.05, 0.95, text, transform=axs[0].transAxes,
                        fontsize=10, verticalalignment='top', bbox=props)
            
    else:
        # --- Define figure ---
        if figsize is None: figsize = (8,5)
        fig = plt.figure(figsize=figsize, dpi=100)
        
        # --- Define the grid for the subplots --- 
        gs = gridspec.GridSpec(1, 2, width_ratios=[20, 0.5],
            height_ratios=[1], hspace=0.1, wspace=0.3)
        
        # --- Subplots ---
        axs = [fig.add_subplot(gs[0, 0])]
        cax = fig.add_subplot(gs[0, 1])  # colorbar axis
        
        # --- Continuous Wavelet Transform ---
        im = axs[0].imshow(np.abs(cwt), extent = [t[0], t[-1], T[-1], T[0]], 
                           aspect='auto', cmap='jet')
        
        # --- Set the ax parameters ---
        axs[0].grid(True, alpha=0.3)
        title = f"Continuous Wavelet Transform | {freq:.1f} GHz"
        axs[0].set_title(title, fontweight='bold')
        axs[0].set_ylabel("Wave period Ts [\u00B5s]")
        axs[0].set_xlabel("Time t [\u00B5s]")
        
        # --- Twin axis for frequency of event ---
        axs_twin = axs[0].twinx()
        axs_twin.set_ylim(axs[0].get_ylim())
        yticks = axs[0].get_yticks()[1:-1]
        axs_twin.set_yticks(yticks)
        axs_twin.set_yticklabels([f"{1/f:.2f}" for f in yticks])
        axs_twin.set_ylabel("Frequency fs [MHz]")
        
        # --- Colorbar ---
        cb = plt.colorbar(im, cax=cax)
        cb.ax.ticklabel_format(style='sci', scilimits=(0, 0))
        cb.set_label("CWT Coefficient")
        
        # --- Event localisation ---
        if (event is not None):
            # scatter: maximum of wavelet transform (gauss fit)
            # event start/end: FWHM along the x axis (gauss fit)
            (i1,i2) = event["FWHM_inds"][f, :]
            
            axs[0].scatter(event["x0"][f]/tu, event["y0"][f]/tu,
                       color = "black")
            axs[0].plot([t[i1], t[i1]], [T[0], T[-1]])
            axs[0].plot([t[i2], t[i2]], [T[0], T[-1]])
        
        # --- Extra information in textbox ---
        if (text is not None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.7)
            axs[0].text(0.05, 0.95, text, transform=axs[0].transAxes,
                        fontsize=10, verticalalignment='top', bbox=props)
        
    
    # --- Show the plot? - Save the plot?
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, axs


def plot_signal():
    return

def plot_density(data, filename = False, frame = 0, show = False, 
                 reflectometer = None, text = None, figsize=(5, 5*1.5)):
    """
    Plot a 2D density field with optional reflectometer information overlay.

    Parameters
    ----------
    data : dict
        Dictionary containing the density data with keys:
        - "X", "Y": coordinate arrays in meters
        - "t": array of time points in seconds
        - "Z": 3D array of density values (time, Y, X)
    filename : str, optional
        If provided, the figure is saved to this file.
        Extension has to be included!!!
    frame : int, default 0
        Time frame index to plot.
    show : bool, default False
        Whether to display the figure interactively.
    reflectometer : object, optional
        Reflectometer object with attributes:
        - setup_map: dict with "x_abs", "y_abs" (not necessary)
        - antenna_pos: antenna position
        - angle: angle in degrees
    text : str, optional
        Text to overlay on the plot.
    figsize : tuple, default (5, 7.5)
        Figure size.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects.
    """
    
    # setting the axis and field data
    ref = reflectometer
    if(ref != None and hasattr(ref, "setup_map")):
        X, Y = ref.setup_map["x_abs"]*1e3, ref.setup_map["y_abs"]*1e3
    else: 
        X, Y = data["X"]*1e3, data["Y"]*1e3
    t, Z = data["t"][frame]*1e6, data["Z"][frame]
    min_val = np.min(Z)
    max_val = np.max(Z)
    
    # Setting the plot data:
    levels = 40
    cmap = "viridis"
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10, 0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z, levels=levels, cmap=cmap,
                          vmin=min_val, vmax=max_val)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    cax2 = cax1.twinx()
    cax2.set_ylim([func.get_plasma_frequency(min_val) * 1e-9, 
                   func.get_plasma_frequency(max_val) * 1e-9])
    cax2.set_ylabel(r'Density [m$^{-3}$] Frequency [GHz]')
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
        ax.plot(xs, ys, c = "black", linestyle= "--")
    
    # Create the appropriate annotations
    ax.set_title("Density field", loc = "center")
    ax.set_xlabel("Radial position x [mm]")
    ax.set_ylabel("Poloidal position y [mm]")
    ax.set_title(f"{round(t,1)} [\u00B5s]", loc = "right")
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def animate_density(data, filename, reduction = 3, show = False, 
                    reflectometer = None, text = None, figsize=(5, 5*1.5)):
    """
    Animate a 2D density field over time with optional reflectometer overlay.

    Parameters
    ----------
    data : dict
        Dictionary containing the density data with keys:
        - "X", "Y": coordinate arrays in meters
        - "t": array of time points in seconds
        - "Z": 3D array of density values (time, Y, X)
    filename : str
        File path to save the animation (supports .gif or .mp4)
        (mp4 needs ffmpeg external software - 
         cannot be used in IDE, only in terminal)
    reduction : int, default 3
        Time step reduction factor for faster animation generation.
    show : bool, default False
        Whether to display the figure interactively.
    reflectometer : object, optional
        Reflectometer object with attributes:
        - setup_map: dict with "x_abs", "y_abs" (not necessary)
        - antenna_pos: antenna position
        - angle: angle in degrees
    text : str, optional
        Text to overlay on the plot.
    figsize : tuple, default (5, 7.5)
        Figure size.

    Returns
    -------
    ani : matplotlib.animation.FuncAnimation
        Animation object.
    """
    
    # setting the axis and field data
    ref = reflectometer
    if(ref != None and hasattr(ref, "setup_map")):
        X, Y = ref.setup_map["x_abs"]*1e3, ref.setup_map["y_abs"]*1e3
    else: 
        X, Y = data["X"]*1e3, data["Y"]*1e3
    t, Z = data["t"][::reduction]*1e6, data["Z"][::reduction,:,:]
    min_val = np.min(Z)
    max_val = np.max(Z)
    
    # Setting the plot data:
    levels = 40
    cmap = "viridis"
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10,0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z[0], levels=levels, cmap=cmap,
                          vmin=min_val, vmax=max_val)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    cax2 = cax1.twinx()
    cax2.set_ylim([func.get_plasma_frequency(min_val) * 1e-9, 
                   func.get_plasma_frequency(max_val) * 1e-9])
    cax2.set_ylabel(r'Density [$m^{-3}$] Frequency [GHz]')
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
    
    # Create the appropriate annotations
    def display(ax):
        ax.set_title("Density field", loc = "center")
        ax.set_xlabel("Radial position x [mm]")
        ax.set_ylabel("Poloidal position y [mm]")
        
        if (text != None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
            ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
                verticalalignment='top', bbox=props)
        
        if(ref != None):
            ax.plot(xs, ys, c = "black", linestyle= "--")
        return contour
        
    # The update function that is responsible for the animation
    def update(frame):
        ax.clear()  # Clear previous frame
        contour = ax.contourf(X, Y, Z[frame], levels=levels, cmap=cmap,
                              vmin=min_val, vmax=max_val)
        ax.set_title(f"{round(t[frame],1)} [\u00B5s]", loc = "right")
        display(ax)
    
    if (show == False): plt.close()
    
    # Create animation with the update function
    ani = animation.FuncAnimation(fig, update, frames=len(t),
                                  interval=100, blit=False)
    if (filename != False):
        if filename.split('.')[1] == 'gif':
            ani.save(filename, writer="pillow", fps=10, dpi=300)
        elif filename.split('.')[1] == 'mp4':
            ani.save(filename, writer="ffmpeg", fps=10, dpi=300)
        else: print("Incorrect file extension is given")
    
    return ani

