# -*- coding: utf-8 -*-
"""
Created on Fri Aug 29 19:26:03 2025

@author: akos
"""

import sys
import os
sys.path.append(os.path.dirname(__file__))
import functions as func


import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib import gridspec



def ref_data(reflectometer):
    """
    Generate a summary string with key properties of a reflectometer.

    Parameters
    ----------
    reflectometer : An object representing a reflectometer. 

    Returns
    -------
    str
        A formatted string summarizing the reflectometer properties, e.g.:
        Solver, Wavemode, Beam waist in mm, and Angle with sign.
    """
    ref = reflectometer
    text = '\n'.join((f"Solver: {ref.solver}",
                      f"Wavemode: {ref.wavemode}",
                      f"Beam w.: {ref.beam_waist_si*1e3} mm",
                      f"Angle: {ref.angle:+}°"))
    return text

def peak_data(data, frequency_index):
    f = frequency_index
    text = '\n'.join(("Event estimation",
        "Coeff.: {:.2f} [1e-3]".format(data[f][0,2]*1e3),
        "Time: {:.2f} [\u00B5s]".format(data[f][0,0]*1e6),
        "Event freq.: {:.3f} [MHz]".format(data[f][0,1]*1e-6)))
    
    return text

def plot_EZ_field(data, filename = None, time = 0, show = False, 
                  reflectometer = None, text = None, figsize=(5, 5*1.5)):
    
    # setting the axis and field data
    ref = reflectometer
    if(ref != None):
        if(hasattr(ref, "setup_map")):
            X, Y = ref.setup_map["X_abs"]*1e3, ref.setup_map["Y_abs"]*1e3
        else:   
            X, Y = np.arange(ref.nx)*ref.dx*1e3, np.arange(ref.ny)*ref.dx*1e3
        
        x_border = (data.shape[1] - ref.nx) // 2
        y_border = (data.shape[0] - ref.ny) // 2

        Z = data[
            y_border : y_border + ref.ny ,
            x_border : x_border + ref.nx
        ]
        
        
    else:       
        X, Y = np.arange(data.shape[1]), np.arange(data.shape[0])
        Z = data
    Z = Z[::-1, :]
    maximum = max(abs(np.max(Z)), abs(np.min(Z)))
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10, 0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z, levels=200, cmap="RdBu_r",
                          vmin=-maximum, vmax=maximum)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
        ax.plot(xs, ys, c = "black", linestyle= "--")
    
    # Create the appropriate annotations
    ax.set_title("Electromagnetic field", loc = "left")
    ax.set_xlabel("Radial position x [mm]")
    ax.set_ylabel("Poloidal position y [mm]")
    ax.set_title(f"{round(time,1)} [\u00B5s]", loc = "right")
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='bottom', bbox=props)
    
    if (show == False): plt.close()
    if (filename != None): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax
    
def plot_amplitude_field(data, filename = None, show = False, text = None,
                         figsize=(8, 5)):
    """
    Plot the amplitude response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "amplitude_field": 2D array of amplitude values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    ampl = ax.contourf(data["time"] *1e6, data["frequencies"], 
                       data["amplitude_field"].T, levels=200, cmap='jet')
    ax.set_title("Amplitude response field")
    ax.set_ylabel("Frequency f [GHz]")
    ax.set_xlabel("Time t [\u00B5s]")
    fig.colorbar(ampl, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != None): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_phase_field(data, filename = None, show = False, text = None,
                     figsize=(8, 5)):
    """
    Plot the phase response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "phase_field": 2D array of phase values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """
    max_val = max(abs(np.max(data["phase_field"])),
                  abs(np.min(data["phase_field"])))
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    phas = ax.contourf(data["time"] *1e6, data["frequencies"], 
                       data["phase_field"].T, levels=200, cmap='coolwarm',
                       vmin=-max_val, vmax=max_val)
    ax.set_title("Phase response field")
    ax.set_ylabel("Frequency f [GHz]")
    ax.set_xlabel("Time t [\u00B5s]")
    fig.colorbar(phas, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != None): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_phase_grad_field(data, filename = None, show = False, text = None,
                          figsize=(8, 5)):
    """
    Plot the phase response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "phase_field": 2D array of phase values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """

    max_val = 2 #max(abs(np.max(data["phase_grad_field"])),


                  #abs(np.min(data["phase_grad_field"])))
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    phas = ax.contourf(data["time"] *1e6, data["frequencies"], 
                       data["phase_grad_field"].T, levels=200, cmap='coolwarm',
                       vmin=-max_val, vmax=max_val)
    ax.set_title("Phase gradient response field")
    ax.set_ylabel("Frequency f [GHz]")
    ax.set_xlabel("Time t [\u00B5s]")
    fig.colorbar(phas, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != None): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_cwt(data, filename = None, show = False, text = None, 
             frequency_index = 0, figsize=None,
             peaks = None, signal = None):
    """
    Plot the Continuous Wavelet Transform as an image plot.

    Parameters
    ----------
    
    """
    fa = frequency_index
    freq = data["frequencies"][data["frequency_indices"][fa]]
    tu = 1e-6 # unit of time (microseconds)
    fu =  1e6 # unit of frequency (MHz)
    cwt = data["matrix"][fa, :, :]
    t = data["time"]/tu
    f = data["freq"]/fu
    
    
    if(signal is not None):
        # --- Define figure ---
        if figsize is None: figsize = (9,6)
        fig = plt.figure(figsize=figsize, dpi=100)
        
        # --- Define the grid for the subplots --- 
        gs = gridspec.GridSpec( 2, 2, width_ratios=[20, 0.5], 
                height_ratios=[0.8, 3], hspace=0.1, wspace=0.12)

        # --- Subplots ---
        axs = [fig.add_subplot(gs[0, 0])]
        axs.append(fig.add_subplot(gs[1, 0], sharex=axs[0]))
        cax = fig.add_subplot(gs[1, 1])  # colorbar axis
        
        # --- Complex signal - time series ---
        S = signal["amplitude_field"] * np.exp(1j * signal["phase_field"])
        S = (S - np.average(S, axis = 0))
        axs[0].plot(signal["time"]/tu, S[:, fa].imag, color='tab:orange')
        axs[0].plot(signal["time"]/tu, S[:, fa].real, color='tab:blue')
        
        # --- Time-frequency field | cwt transform ---
        im = axs[1].pcolormesh(t,f,np.abs(cwt), shading='gouraud', cmap='jet')
        # t - time series, f - wavelet frequency
        
        # --- Set the ax parameters ---
        title = (f"Complex signal and its Continuous Wavelet Transform" +
                 f" | {freq:.1f} GHz")
        axs[0].set_title(title, fontweight='bold')
        axs[0].set_ylabel("Signal")
        axs[0].grid(True, alpha=0.3)
        axs[0].tick_params(axis='x', which='both', bottom=0, labelbottom=0)
        axs[0].legend([r"$\Re$", r"$\Im$"], loc = 'lower left')
        axs[1].set_ylabel("Frequency fs [MHz]")
        axs[1].set_xlabel("Time t [\u00B5s]")
        axs[1].grid(True, alpha=0.3)
        
        # --- Colorbar ---
        cb = plt.colorbar(im, cax=cax)
        cb.ax.ticklabel_format(style='sci', scilimits=(0, 0))
        cb.set_label("CWT Coefficient")
        
        # --- Event localisation ---
        if (peaks is not None):
            # scatter: maximum of wavelet transform (peak searching algorithm)
            axs[1].scatter(peaks[fa][:, 0]/tu, peaks[fa][:, 1]/fu, c="black")
        
        # Extra infromation in textbox
        if (text is not None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.7)
            axs[1].text(0.05, 0.95, text, transform=axs[1].transAxes,
                        fontsize=10, verticalalignment='top', bbox=props)
            
    else:
        # --- Define figure ---
        if figsize is None: figsize = (8,5)
        fig = plt.figure(figsize=figsize, dpi=100)
        
        # --- Define the grid for the subplots --- 
        gs = gridspec.GridSpec(1, 2, width_ratios=[20, 0.5],
            height_ratios=[1], hspace=0.1, wspace=0.3)
        
        # --- Subplots ---
        axs = [fig.add_subplot(gs[0, 0])]
        cax = fig.add_subplot(gs[0, 1])  # colorbar axis
        
        # --- Continuous Wavelet Transform ---
        im = axs[1].pcolormesh(t,f,np.abs(cwt), shading='gouraud', cmap='jet')
        # t - time series, f - wavelet frequency
        
        # --- Set the ax parameters ---
        axs[0].grid(True, alpha=0.3)
        title = f"Continuous Wavelet Transform | {freq:.1f} GHz"
        axs[0].set_title(title, fontweight='bold')
        axs[0].set_ylabel("Frequency fs [MHz]")
        axs[0].set_xlabel("Time t [\u00B5s]")
        
        # --- Colorbar ---
        cb = plt.colorbar(im, cax=cax)
        cb.ax.ticklabel_format(style='sci', scilimits=(0, 0))
        cb.set_label("CWT Coefficient")
        
        # --- Event localisation ---
        if (peaks is not None):
            # scatter: maximum of wavelet transform (peak searching algorithm)
            axs[1].scatter(peaks[fa][:, 0]/tu, peaks[fa][:, 1]/fu, c="black")
        
        # --- Extra information in textbox ---
        if (text is not None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.7)
            axs[0].text(0.05, 0.95, text, transform=axs[0].transAxes,
                        fontsize=10, verticalalignment='top', bbox=props)
        
    
    # --- Show the plot? - Save the plot?
    if (show == False): plt.close()
    if (filename != None): 
        fig.savefig(filename, dpi=300)
    
    return fig, axs

def plot_stft(data, filename = None, show = False, text = None, 
             frequency_index = 0, figsize=None,
             peaks = None, signal = None):
    """
    Plot the Short-Time Fourier Transform as an image plot.

    Parameters
    ----------
    
    """
    fa = frequency_index
    freq = data["frequencies"][data["frequency_indices"][fa]]
    tu = 1e-6 # unit of time (microseconds)
    fu =  1e6 # unit of frequency (MHz)
    cwt = data["matrix"][fa, :, :]
    t = data["time"]/tu
    f = data["freq"]/fu
    
    
    if(signal is not None):
        # --- Define figure ---
        if figsize is None: figsize = (9,6)
        fig = plt.figure(figsize=figsize, dpi=100)
        
        # --- Define the grid for the subplots --- 
        gs = gridspec.GridSpec( 2, 2, width_ratios=[20, 0.5], 
                height_ratios=[0.8, 3], hspace=0.1, wspace=0.12)

        # --- Subplots ---
        axs = [fig.add_subplot(gs[0, 0])]
        axs.append(fig.add_subplot(gs[1, 0], sharex=axs[0]))
        cax = fig.add_subplot(gs[1, 1])  # colorbar axis
        
        # --- Complex signal - time series ---
        S = signal["amplitude_field"] * np.exp(1j * signal["phase_field"])
        S = (S - np.average(S, axis = 0))
        axs[0].plot(signal["time"]/tu, S[:, fa].imag, color='tab:orange')
        axs[0].plot(signal["time"]/tu, S[:, fa].real, color='tab:blue')
        
        # --- Time-frequency field | cwt transform ---
        im = axs[1].pcolormesh(t,f,np.abs(cwt), shading='gouraud', cmap='jet')
        # t - time series, f - Fourier frequency
        
        # --- Set the ax parameters ---
        title = (f"Complex signal and its Short-Time Fourier Transform" +
                 f" | {freq:.1f} GHz")
        axs[0].set_title(title, fontweight='bold')
        axs[0].set_ylabel("Signal")
        axs[0].grid(True, alpha=0.3)
        axs[0].tick_params(axis='x', which='both', bottom=0, labelbottom=0)
        axs[0].legend([r"$\Re$", r"$\Im$"], loc = 'lower left')
        axs[1].set_ylabel("Frequency fs [MHz]")
        axs[1].set_xlabel("Time t [\u00B5s]")
        axs[1].grid(True, alpha=0.3)
        
        # --- Colorbar ---
        cb = plt.colorbar(im, cax=cax)
        cb.ax.ticklabel_format(style='sci', scilimits=(0, 0))
        cb.set_label("STFT Coefficient")
        
        # --- Event localisation ---
        if (peaks is not None):
            # scatter: maximum of Fourier transform (peak searching algorithm)
            axs[1].scatter(peaks[fa][:, 0]/tu, peaks[fa][:, 1]/fu, c="black")
        
        # Extra infromation in textbox
        if (text is not None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.7)
            axs[1].text(0.05, 0.95, text, transform=axs[1].transAxes,
                        fontsize=10, verticalalignment='top', bbox=props)
            
    else:
        # --- Define figure ---
        if figsize is None: figsize = (8,5)
        fig = plt.figure(figsize=figsize, dpi=100)
        
        # --- Define the grid for the subplots --- 
        gs = gridspec.GridSpec(1, 2, width_ratios=[20, 0.5],
            height_ratios=[1], hspace=0.1, wspace=0.3)
        
        # --- Subplots ---
        axs = [fig.add_subplot(gs[0, 0])]
        cax = fig.add_subplot(gs[0, 1])  # colorbar axis
        
        # --- Continuous Wavelet Transform ---
        im = axs[1].pcolormesh(t,f,np.abs(cwt), shading='gouraud', cmap='jet')
        # t - time series, f - Fourier frequency
        
        # --- Set the ax parameters ---
        axs[0].grid(True, alpha=0.3)
        title = f"Short-Time Fourier Transform | {freq:.1f} GHz"
        axs[0].set_title(title, fontweight='bold')
        axs[0].set_ylabel("Frequency fs [MHz]")
        axs[0].set_xlabel("Time t [\u00B5s]")
        
        # --- Colorbar ---
        cb = plt.colorbar(im, cax=cax)
        cb.ax.ticklabel_format(style='sci', scilimits=(0, 0))
        cb.set_label("STFT Coefficient")
        
        # --- Event localisation ---
        if (peaks is not None):
            # scatter: maximum of Fourier transform (peak searching algorithm)
            axs[1].scatter(peaks[fa][:, 0]/tu, peaks[fa][:, 1]/fu, c="black")
        
        # --- Extra information in textbox ---
        if (text is not None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.7)
            axs[0].text(0.05, 0.95, text, transform=axs[0].transAxes,
                        fontsize=10, verticalalignment='top', bbox=props)
        

    # --- Show the plot? - Save the plot?
    if (show == False): plt.close()
    if (filename != None): 
        fig.savefig(filename, dpi=300)
    
    return fig, axs


def plot_density(data, filename = None, frame = 0, show = False, 
                 reflectometer = None, text = None, figsize=(5, 5*1.5)):
    """
    Plot a 2D density field with optional reflectometer information overlay.

    Parameters
    ----------
    data : dict
        Dictionary containing the density data with keys:
        - "X", "Y": coordinate arrays in meters
        - "t": array of time points in seconds
        - "Z": 3D array of density values (time, Y, X)
    filename : str, optional
        If provided, the figure is saved to this file.
        Extension has to be included!!!
    frame : int, default 0
        Time frame index to plot.
    show : bool, default False
        Whether to display the figure interactively.
    reflectometer : object, optional
        Reflectometer object with attributes:
        - setup_map: dict with "x_abs", "y_abs" (not necessary)
        - antenna_pos: antenna position
        - angle: angle in degrees
    text : str, optional
        Text to overlay on the plot.
    figsize : tuple, default (5, 7.5)
        Figure size.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects.
    """
    
    # setting the axis and field data
    ref = reflectometer
    if(ref != None and hasattr(ref, "setup_map")):
        X, Y = ref.setup_map["x_abs"]*1e3, ref.setup_map["y_abs"]*1e3
    else: 
        X, Y = data["X"]*1e3, data["Y"]*1e3
    t, Z = data["t"][frame]*1e6, data["Z"][frame]
    min_val = np.min(Z)
    max_val = np.max(Z)
    
    # Setting the plot data:
    levels = 40
    cmap = "viridis"
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10, 0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z, levels=levels, cmap=cmap,
                          vmin=min_val, vmax=max_val)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    cax2 = cax1.twinx()
    cax2.set_ylim([func.get_plasma_frequency(min_val) * 1e-9, 
                   func.get_plasma_frequency(max_val) * 1e-9])
    cax2.set_ylabel(r'Density [m$^{-3}$] Frequency [GHz]')
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
        ax.plot(xs, ys, c = "black", linestyle= "--")
    
    # Create the appropriate annotations
    ax.set_title("Density field", loc = "left")
    ax.set_xlabel("Radial position x [mm]")
    ax.set_ylabel("Poloidal position y [mm]")
    ax.set_title(f"{round(t,1)} [\u00B5s]", loc = "right")
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != None): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def animate_density(data, filename, reduction = 3, show = False, 
                    reflectometer = None, text = None, figsize=(5, 5*1.5)):
    """
    Animate a 2D density field over time with optional reflectometer overlay.

    Parameters
    ----------
    data : dict
        Dictionary containing the density data with keys:
        - "X", "Y": coordinate arrays in meters
        - "t": array of time points in seconds
        - "Z": 3D array of density values (time, Y, X)
    filename : str
        File path to save the animation (supports .gif or .mp4)
        (mp4 needs ffmpeg external software - 
         cannot be used in IDE, only in terminal)
    reduction : int, default 3
        Time step reduction factor for faster animation generation.
    show : bool, default False
        Whether to display the figure interactively.
    reflectometer : object, optional
        Reflectometer object with attributes:
        - setup_map: dict with "x_abs", "y_abs" (not necessary)
        - antenna_pos: antenna position
        - angle: angle in degrees
    text : str, optional
        Text to overlay on the plot.
    figsize : tuple, default (5, 7.5)
        Figure size.

    Returns
    -------
    ani : matplotlib.animation.FuncAnimation
        Animation object.
    """
    
    # setting the axis and field data
    ref = reflectometer
    if(ref != None and hasattr(ref, "setup_map")):
        X, Y = ref.setup_map["x_abs"]*1e3, ref.setup_map["y_abs"]*1e3
    else: 
        X, Y = data["X"]*1e3, data["Y"]*1e3
    t, Z = data["t"][::reduction]*1e6, data["Z"][::reduction,:,:]
    min_val = np.min(Z)
    max_val = np.max(Z)
    
    # Setting the plot data:
    levels = 40
    cmap = "viridis"
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10,0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z[0], levels=levels, cmap=cmap,
                          vmin=min_val, vmax=max_val)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    cax2 = cax1.twinx()
    cax2.set_ylim([func.get_plasma_frequency(min_val) * 1e-9, 
                   func.get_plasma_frequency(max_val) * 1e-9])
    cax2.set_ylabel(r'Density [$m^{-3}$] Frequency [GHz]')
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
    
    # Create the appropriate annotations
    def display(ax):
        ax.set_title("Density field", loc = "center")
        ax.set_xlabel("Radial position x [mm]")
        ax.set_ylabel("Poloidal position y [mm]")
        
        if (text != None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
            ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
                verticalalignment='top', bbox=props)
        
        if(ref != None):
            ax.plot(xs, ys, c = "black", linestyle= "--")
        return contour
        
    # The update function that is responsible for the animation
    def update(frame):
        ax.clear()  # Clear previous frame
        contour = ax.contourf(X, Y, Z[frame], levels=levels, cmap=cmap,
                              vmin=min_val, vmax=max_val)
        ax.set_title(f"{round(t[frame],1)} [\u00B5s]", loc = "right")
        display(ax)
    
    if (show == False): plt.close()
    
    # Create animation with the update function
    ani = animation.FuncAnimation(fig, update, frames=len(t),
                                  interval=100, blit=False)
    if (filename != None):
        if filename.split('.')[1] == 'gif':
            ani.save(filename, writer="pillow", fps=10, dpi=300)
        elif filename.split('.')[1] == 'mp4':
            ani.save(filename, writer="ffmpeg", fps=10, dpi=300)
        else: print("Incorrect file extension is given")
    
    return ani

