# -*- coding: utf-8 -*-
"""
Created on Fri Aug 29 19:26:03 2025

@author: akos
"""

import sys
import os
sys.path.append(os.path.dirname(__file__))
import functions as func


import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation


def ref_data(reflectometer):
    """
    Generate a summary string with key properties of a reflectometer.

    Parameters
    ----------
    reflectometer : An object representing a reflectometer. 

    Returns
    -------
    str
        A formatted string summarizing the reflectometer properties, e.g.:
        Solver, Wavemode, Beam waist in mm, and Angle with sign.
    """
    ref = reflectometer
    text = '\n'.join((f"Solver: {ref.solver}",
                      f"Wavemode: {ref.wavemode}",
                      f"Beam w.: {ref.beam_waist_si*1e3} mm",
                      f"Angle: {ref.angle:+}°"))
    return text

def plot_amplitude_field(data, filename = False, show = False, text = None,
                         figsize=(8, 5)):
    """
    Plot the amplitude response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "amplitude_field": 2D array of amplitude values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    ampl = ax.contourf(data["frequencies"], data["time"] *1e6, 
                       data["amplitude_field"], levels=200, cmap='jet')
    ax.set_title("Amplitude response field")
    ax.set_xlabel("Frequency f [GHz]")
    ax.set_ylabel("Time t [\u00B5s]")
    fig.colorbar(ampl, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_phase_field(data, filename = False, show = False, text = None,
                     figsize=(8, 5)):
    """
    Plot the phase response field as a contour plot.

    Parameters
    ----------
    data : dict
        Dictionary with keys:
        - "frequencies": array-like, frequency values in Hz
        - "time": array-like, time values in seconds
        - "phase_field": 2D array of phase values
    filename : str, optional
        If provided, the figure will be saved to this file. 
        Extension has to be included!!!
    show : bool, default False
        Whether to display the figure interactively.
    text : str, optional
        Text to overlay on the plot. Generated by ref_data(...)
    figsize : tuple, default (8, 5)
        Figure size in inches.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects of the plot.
    """
    
    fig, ax = plt.subplots(figsize=figsize, constrained_layout=True)
    phas = ax.contourf(data["frequencies"], data["time"] *1e6, 
                       data["phase_field"], levels=200, cmap='coolwarm')
    ax.set_title("Phase response field")
    ax.set_xlabel("Frequency f [GHz]")
    ax.set_ylabel("Time t [\u00B5s]")
    fig.colorbar(phas, ax=ax)
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def plot_density(data, filename = False, frame = 0, show = False, 
                 reflectometer = None, text = None, figsize=(5, 5*1.5)):
    """
    Plot a 2D density field with optional reflectometer information overlay.

    Parameters
    ----------
    data : dict
        Dictionary containing the density data with keys:
        - "X", "Y": coordinate arrays in meters
        - "t": array of time points in seconds
        - "Z": 3D array of density values (time, Y, X)
    filename : str, optional
        If provided, the figure is saved to this file.
        Extension has to be included!!!
    frame : int, default 0
        Time frame index to plot.
    show : bool, default False
        Whether to display the figure interactively.
    reflectometer : object, optional
        Reflectometer object with attributes:
        - setup_map: dict with "x_abs", "y_abs" (not necessary)
        - antenna_pos: antenna position
        - angle: angle in degrees
    text : str, optional
        Text to overlay on the plot.
    figsize : tuple, default (5, 7.5)
        Figure size.

    Returns
    -------
    fig, ax : matplotlib.figure.Figure, matplotlib.axes.Axes
        Figure and axes objects.
    """
    
    # setting the axis and field data
    ref = reflectometer
    if(ref != None and hasattr(ref, "setup_map")):
        X, Y = ref.setup_map["x_abs"]*1e3, ref.setup_map["y_abs"]*1e3
    else: 
        X, Y = data["X"]*1e3, data["Y"]*1e3
    t, Z = data["t"][frame]*1e6, data["Z"][frame]
    min_val = np.min(Z)
    max_val = np.max(Z)
    
    # Setting the plot data:
    levels = 40
    cmap = "viridis"
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10, 0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z, levels=levels, cmap=cmap,
                          vmin=min_val, vmax=max_val)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    cax2 = cax1.twinx()
    cax2.set_ylim([func.get_plasma_frequency(min_val) * 1e-9, 
                   func.get_plasma_frequency(max_val) * 1e-9])
    cax2.set_ylabel('Density [] Frequency [GHz]')
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
        ax.plot(xs, ys, c = "black", linestyle= "--")
    
    # Create the appropriate annotations
    ax.set_title("Density field", loc = "center")
    ax.set_xlabel("Radial position x [mm]")
    ax.set_ylabel("Poloidal position y [mm]")
    ax.set_title(f"{round(t,1)} [\u00B5s]", loc = "right")
    
    if (text != None):
        props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
        ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    if (show == False): plt.close()
    if (filename != False): 
        fig.savefig(filename, dpi=300)
    
    return fig, ax

def animate_density(data, filename, reduction = 3, show = False, 
                    reflectometer = None, text = None, figsize=(5, 5*1.5)):
    """
    Animate a 2D density field over time with optional reflectometer overlay.

    Parameters
    ----------
    data : dict
        Dictionary containing the density data with keys:
        - "X", "Y": coordinate arrays in meters
        - "t": array of time points in seconds
        - "Z": 3D array of density values (time, Y, X)
    filename : str
        File path to save the animation (supports .gif or .mp4)
        (mp4 needs ffmpeg external software - 
         cannot be used in IDE, only in terminal)
    reduction : int, default 3
        Time step reduction factor for faster animation generation.
    show : bool, default False
        Whether to display the figure interactively.
    reflectometer : object, optional
        Reflectometer object with attributes:
        - setup_map: dict with "x_abs", "y_abs" (not necessary)
        - antenna_pos: antenna position
        - angle: angle in degrees
    text : str, optional
        Text to overlay on the plot.
    figsize : tuple, default (5, 7.5)
        Figure size.

    Returns
    -------
    ani : matplotlib.animation.FuncAnimation
        Animation object.
    """
    
    # setting the axis and field data
    ref = reflectometer
    if(ref != None and hasattr(ref, "setup_map")):
        X, Y = ref.setup_map["x_abs"]*1e3, ref.setup_map["y_abs"]*1e3
    else: 
        X, Y = data["X"]*1e3, data["Y"]*1e3
    t, Z = data["t"][::reduction]*1e6, data["Z"][::reduction,:,:]
    min_val = np.min(Z)
    max_val = np.max(Z)
    
    # Setting the plot data:
    levels = 40
    cmap = "viridis"
    
    # Set up figure layout and color map
    fig, (ax, cax1) = plt.subplots(figsize=figsize, ncols=2,
                                   gridspec_kw={"width_ratios":[10,0.5]},
                                   constrained_layout=True)
    # fig.subplots_adjust(left=0.15, right=0.95, top=0.95, bottom=0.08)
    contour = ax.contourf(X, Y, Z[0], levels=levels, cmap=cmap,
                          vmin=min_val, vmax=max_val)
    
    # Create the colorbar
    cbar = plt.colorbar(contour, cax=cax1)
    cax2 = cax1.twinx()
    cax2.set_ylim([func.get_plasma_frequency(min_val) * 1e-9, 
                   func.get_plasma_frequency(max_val) * 1e-9])
    cax2.set_ylabel('Density [] Frequency [GHz]')
    
    # If a reflectometer is defined, its path is displayed:
    if(ref != None):
        pos, dist = ref.antenna_pos * 1e3 + Y[0], (X[-1] - X[0]) * 0.8
        xs = (X[0], X[0] + dist)
        ys = (pos, np.tan(ref.angle / 180 * np.pi) * abs(dist) + pos)
    
    # Create the appropriate annotations
    def display(ax):
        ax.set_title("Density field", loc = "center")
        ax.set_xlabel("Radial position x [mm]")
        ax.set_ylabel("Poloidal position y [mm]")
        
        if (text != None):
            props = dict(boxstyle='round', facecolor='grey', alpha=0.5)
            ax.text(0.05, 0.95, text, transform=ax.transAxes, fontsize=10,
                verticalalignment='top', bbox=props)
        
        if(ref != None):
            ax.plot(xs, ys, c = "black", linestyle= "--")
        return contour
        
    # The update function that is responsible for the animation
    def update(frame):
        ax.clear()  # Clear previous frame
        contour = ax.contourf(X, Y, Z[frame], levels=levels, cmap=cmap,
                              vmin=min_val, vmax=max_val)
        ax.set_title(f"{round(t[frame],1)} [\u00B5s]", loc = "right")
        display(ax)
    
    if (show == False): plt.close()
    
    # Create animation with the update function
    ani = animation.FuncAnimation(fig, update, frames=len(t),
                                  interval=100, blit=False)
    if (filename != False):
        if filename.split('.')[1] == 'gif':
            ani.save(filename, writer="pillow", fps=10, dpi=300)
        elif filename.split('.')[1] == 'mp4':
            ani.save(filename, writer="ffmpeg", fps=10, dpi=300)
        else: print("Incorrect file extension is given")
    
    return ani